// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz22VkFbYvXXYbz8KZowGNSiWjP2QpP4s',
    appId: '1:272425722153:web:a676f8dbba95c158a41738',
    messagingSenderId: '272425722153',
    projectId: 'cstain',
    authDomain: 'cstain.firebaseapp.com',
    storageBucket: 'cstain.appspot.com',
    measurementId: 'G-3VNEPEM7RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vJhXJP16__gYp6jjJhnZf2WJOs51fjw',
    appId: '1:272425722153:android:6c28eb9bad6e197ca41738',
    messagingSenderId: '272425722153',
    projectId: 'cstain',
    storageBucket: 'cstain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk2HWWmbWM3PegFK4XjVZMxodUEpYbjpw',
    appId: '1:272425722153:ios:c0e035d6208f8931a41738',
    messagingSenderId: '272425722153',
    projectId: 'cstain',
    storageBucket: 'cstain.appspot.com',
    iosBundleId: 'com.example.cstain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk2HWWmbWM3PegFK4XjVZMxodUEpYbjpw',
    appId: '1:272425722153:ios:c0e035d6208f8931a41738',
    messagingSenderId: '272425722153',
    projectId: 'cstain',
    storageBucket: 'cstain.appspot.com',
    iosBundleId: 'com.example.cstain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz22VkFbYvXXYbz8KZowGNSiWjP2QpP4s',
    appId: '1:272425722153:web:7b304e0b55a7ef4ea41738',
    messagingSenderId: '272425722153',
    projectId: 'cstain',
    authDomain: 'cstain.firebaseapp.com',
    storageBucket: 'cstain.appspot.com',
    measurementId: 'G-GV3P0FJWH5',
  );
}
